### ISSUE TITLE
Imagem não aparece

### ISSUE THREAD

**Issue by fernandounger** [mateus-maximo/Dados-Climaticos#2]
O caminho especificado não reconhece a imagem da aplicação.

**Comment by mateus-maximo** [comment]
Boa tarde, Fernando. Qual seria o problema?

**Comment by fernandounger** [comment]
Boa tarde, Mateus!

No seu arquivo CSS, na linha 13, tem a seguinte propriedade e seu valor:

```css
background-image: url('/images/bg.jpg');
```
O problema é que o caminho especificado não chega reconhecer a imagem de fundo do seu projeto de dados climáticos ```/images/``` , para resolver isso, basta apenas colocar o caminho relativo para a localização da imagem a partir do arquivo atual usando ```./images/bg.jpg```.
